---
title: "Estudio de caso"
author: "H y G"
format: pdf
editor: visual
---
```{r}
install.packages("readxl")
```

```{r}
Datos<-read.csv("estudio.csv")
```
```{r}
colnames(Datos)<-c("Entidad","Total_unidades","Unidades_sin","Unidades_tur")
```
```{r}
estados_costeños <- c("Baja California", "Baja California Sur", "Campeche", "Chiapas", "Colima", "Guerrero","Sonora", "Sinaloa", "Nayarit", "Jalisco", "Michoacán","Oaxaca", "Quintana Roo", "Yucatán", "Tabasco", "Veracruz", "Tamaulipas" )
Datos$Costero <- ifelse(Datos$Entidad %in% estados_costeños, 1, 0)
```
```{r}
summary(Datos)
```
```{r}
install.packages("ggplot")
```
```{r}
install.packages("ggplot2")
library(ggplot2)
```
```{r}
ggplot(Datos, aes(x = factor(Costero, labels = c("No Costero", "Costero")), y = Unidades_tur, fill = factor(Costero))) +
  geom_bar(stat = "identity") +
geom_bar(stat = "identity") +
labs(title = "Unidades de Producción con Actividades Turísticas",
x = "Ubicación", y = "Cantidad de Unidades") +
scale_fill_manual(values = c("purple", "blue")) +
theme_minimal()
```
```{r}
ggplot(Datos, aes(x = factor(Costero, labels = c("No Costero", "Costero")), y = Unidades_sin, fill = factor(Costero))) +
  geom_bar(stat = "identity") +
  labs(title = "Unidades de Producción sin Actividades Agropecuarias y Forestales",
       x = "Ubicación", y = "Cantidad de Unidades") +
  scale_fill_manual(values = c("purple", "blue")) +
  theme_minimal()

```
```{r}
modelo_turismo <- glm(Unidades_tur ~ Costero, data = Datos, family = poisson)
summary(modelo_turismo)

modelo_noagroforestales <- glm(Unidades_sin ~ Costero, data = Datos, family = poisson)
summary(modelo_noagroforestales) #solo para ver la relación 
```
```{r}
modelo_costero<- lm(Unidades_tur ~ Unidades_sin + Costero, data= Datos)
summary(modelo_costero) #esto explica que las unidades turisticas estan relacionadas en si hay o no unidades de producción agropecuarias y forestales, con modelo de regresión multiple
```
```{r}
modelo_costero<- lm(Unidades_tur ~  Costero, data= Datos)
summary(modelo_costero)
```


